{"cells":[{"cell_type":"markdown","metadata":{"id":"HhNyM6YQEPTZ"},"source":["# Errors Handling - Synopsis\n","\n","In this unit we will learn that:\n","\n","1. **Programming errors** are inevitable as you develop code.\n","\n","    1. Syntax errors are easy to find (the code does not run or crashes)\n","    \n","    2. Type, Name, Index, Value, and Attribute errors are easy to find (the code crashes)\n","    \n","    3. Logical errors can be extremely hard to identify (the code may run and the results may appear plausible)\n","    \n","2. **Errors messages** can be extremely helpful in finding and correcting syntax errors and calculation or variable type errors.\n","\n","3. **Error handling** commands enable code to exit graciously when an exceptions occur.\n","\n","4. **Unit testing** is essential in order to avoid logical errors.\n","\n","\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"i9WFrgP5EPTc"},"source":["# Programming and Errors\n","\n","As as programs grow in complexity and the number of lines of code and instructions for the computer to carry out grow, the more likely it is that our code will have errors. Already you've seen some errors as we've learned what can and can't be done, but now it's time look at errors in a more systematic manner.\n","\n","Just like there are different data types, there are also different error types. Having different error types helps us to more easily identify what has gone wrong in our code.\n","\n","## Syntax errors\n","\n","Like all programming languages, Python needs you to write code in a **syntaxically correct manner** so that it can understand your commands and translate them to the machine. If you don't follow the correct syntax in your code, such as not having matched parentheses, brackets, or quotations marks, your code will generate a `SyntaxError`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"cIN69ZbEEPTd"},"outputs":[],"source":["value = 3\n","sentence = 'I am a sentence\n","print(value)"]},{"cell_type":"markdown","metadata":{"id":"RNyXZZoyEPTi"},"source":["What you're seeing above is the **exception** and the **traceback**. The first part is the **traceback**.\n","\n","`File \"<ipython-input-2-a6097ed4dc2e>\"`\n","\n","It tells us the \"file\" that the compiler was processing when the error occurred. Since we are using an Jupyter notebook and are not calling any functions defined in external files, this line is not providing any additional information to us.\n","\n","We then learn that the error occurred at\n","\n","`line 2`\n","\n","and that the parsing problem occurred at\n","\n","`sentence = 'I am a sentence`\n","\n","**Be aware that this information isn't always accurate**. Depending upon the type of error and the complexity of the line of code, the actual error could be above or below where it points out that the error is occurring.\n","\n","The second part is the **exception**.\n","\n","`SyntaxError: EOL while scanning string literal`\n","\n","It tells us what issue generated the error. In this case, we have a `SyntaxError` because Python reached the end of the line (`EOL`) while it was scanning the string we started with `'` and it couldn't find the closing `'`.\n","\n","## Indentation errors\n","\n","Another type of syntax error that can occur in Python is an `Indentation Error`.   Consider the following code snippet:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"c9GCH8C1EPTj"},"outputs":[],"source":["for i in range(3):\n","  j = i * 2          # After : at least one space/indentation is required for the code blocks.\n","    print(i, j)\n"]},{"cell_type":"markdown","metadata":{"id":"kdzad5qrEPTn"},"source":["The third line in the code snippet - `print(i, j)` - should be aligned vertically with the beginning of the second line - `j = i * 2` - but it is not."]},{"cell_type":"markdown","metadata":{"id":"0AVkxXbjEPTp"},"source":["## Type errors\n","\n","A very common Python error is the `TypeError`. This happens when we try to use a method that is for one data type on another data type that does not support it. Remember how strings cannot be subtracted or divided?"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"jfMZcnRVEPTq"},"outputs":[],"source":["new_string = 'cat' + 'dog'\n","print(new_string)\n","new_string = 'cat' + 'dog' + 5\n","print(new_string)"]},{"cell_type":"markdown","metadata":{"id":"s5biRIZLEPTx"},"source":["\n","## Name errors\n","\n","Variables in Python must be initialized before they can be used.  If we try to use a variable prior to initialization, we will get a `NameError`. For example, imagine we try to use the new variable `party`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TPQ7Y2XdEPTy"},"outputs":[],"source":["party = 5\n","print( party2 )"]},{"cell_type":"markdown","metadata":{"id":"qmh-xpsxEPT1"},"source":["## Index errors\n","\n","\n","As you will remember, specific characters in a string can be accessed using an `index`. The index ranges from 0 to the length of the string minus one.  If we try to access a character in a string by index, and that index doesn't exist in the variable, the Python interpreter returns an `IndexError`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Xqli--jpEPT2"},"outputs":[],"source":["example_string = 'abcdefg'\n","print(len(example_string))\n","print( example_string[2] )\n","print( example_string[2:12] )\n","print( example_string[12] )"]},{"cell_type":"markdown","metadata":{"id":"9HItuXOjEPT5"},"source":["A similar type of error is a `KeyError` which can occur when dealing with a very powerful data type we will describe later;   dictionaries.\n","\n","## Value errors\n","\n","Functions (or methods) in Python are written to only work with arguments of specific types. If we call a function with a non-compliant argument, we get a `ValueError`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"OG69rxhvEPT7"},"outputs":[],"source":["example_string = input(\"Enter a string: \")\n","\n","print( example_string )\n","print( type(example_string) ) # data type\n","print( len(example_string) ) # for the length\n","float(example_string)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ESJWOPOWbjVq"},"outputs":[],"source":["x = int(input(\"Enter a number: \"))\n","print(x+x)"]},{"cell_type":"markdown","metadata":{"id":"XVph-oWhEPT-"},"source":["## Attribute errors\n","\n","Many Python objects have attributes that can be easily retrieved using the name of the attribute. For example, an attribute of a string is its capitalized form or its upper case form. However, while one can obtain the length of a string using the default function `len()`, strings do not have a `len()` attribute."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"-CaAKNfsEPT_"},"outputs":[],"source":["example_string = \"pyTHoN proGRAMM1ng\"\n","\n","print( example_string.title() )  # convert 1st char of each word to uppercase\n","print( example_string.capitalize() )  # converts 1st char of the string as uppercase\n","print( example_string.upper() )  # converts all characters to uppercase\n","print( example_string.lower() )  # converts all characters to lower case\n","print( len(example_string) )    # counts and prints the number of characters\n","print( example_string.len() )   # ERROR"]},{"cell_type":"markdown","metadata":{"id":"TFeEn_cIEPUB"},"source":["The examples above illustrate some of the errors that you are most likely to encounter when programming. For the full list of exceptions and errors you can refer to the official Python documentation.\n","\n","Python Built-in Exceptions docs:\n","https://docs.python.org/3.4/library/exceptions.html\n","\n","Python Error Handling docs:\n","https://docs.python.org/3.4/tutorial/errors.html\n","\n","The important thing to remember is to look at the error message. It takes a little bit of practice but pretty soon you'll be able to see that the Python interpreter is trying its hardest to tell you exactly where and why you made a mistake."]},{"cell_type":"markdown","metadata":{"id":"nlhpLAvuEPUC"},"source":["+++"]},{"cell_type":"markdown","metadata":{"id":"GgVKi_8iEPUD"},"source":["## Handling exceptions\n","\n","Code with syntax errors will not run. However, code with other types of errors will still run until it comes upon an exception, at which point it will crash.  This is not nice. As much as possible, you will want to prevent your code from crashing so that you can save whatever information has been generated up to that point and also that you can tell the user of the program WHY the code crashed.\n","\n","Consider the following situation: We want to use the `input()` function to ask for a number and then return the square of that number."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"WLhAqGZxEPUE"},"outputs":[],"source":["number_to_square = input(\"What number do you want to know the square of? \")\n","print( type(number_to_square) )\n","\n","# Note that number_to_square is a string, in order to perform calculations with it, we have to transform it to an integer\n","number = int(number_to_square)\n","\n","print(\"Your number squared is \", number**2)"]},{"cell_type":"markdown","metadata":{"id":"w4F2HbHlEPUG"},"source":["But what would happen if you entered 'a' instead of 3? Try it!\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n","\n","You got a `ValueError` because you can't convert 'a' to an integer.\n","\n","In order to avoid having the program crash, we can use the `try ... except ...` construction so that we test for possible errors and avoid the crash."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"-79BfFgoEPUH"},"outputs":[],"source":["number_to_square = input(\"What number do you want to know the square of? \")\n","print( type(number_to_square) )\n","\n","# Note that number_to_square is a string, in order to perform calculations with it, we have to transform it to an integer\n","try:\n","    number = int(number_to_square)\n","    print(\"Your number squared is \", number**2)\n","except ValueError:\n","    print(\"You didn't enter an integer!\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"tw5xrtdTmW4-"},"outputs":[],"source":["# Simple example\n","\n","var1 = 5\n","try:\n","  print(var2)\n","except NameError:\n","  print('I think you entered the wrong variable name in the code above')\n"]},{"cell_type":"markdown","metadata":{"id":"rIaphlGtEPUJ"},"source":["When you are writing code that takes as inputs information provided by a user or from a source over which you have no control, **it is crucial that you test your code for all possible types of inputs**. That way you will prevent the user from having the pleasure of making your code crash.\n","\n","However, if the functions in your code are taking as input only information that is generated internally by your code, you will not need to make those checks.  **This does not mean that your code will not generate exceptions**. Your code might very well generate exceptions because of logical errors in your code: **That is your code might not be doing what you expect it to be doing!**\n","\n"]},{"cell_type":"markdown","metadata":{"id":"yhAUZo-AbjVs"},"source":["## Explore more (Additional)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TQpjGfblbjVs"},"outputs":[],"source":["try:\n","    name = 'Bob'\n","    name += 5       # change 5 to 'y' and run again. It is TypeError\n","    print(name2)\n","\n","except (NameError, TypeError) as error:\n","    print(error)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"sytotRRQbjVs"},"outputs":[],"source":["a,b=1,0\n","\n","try:\n","    print(a/b)\n","    print(10+10)    # change one of the 10 to a string\n","except TypeError:\n","    print(\"You added values of incompatible types\")\n","except ZeroDivisionError:\n","    print(\"You divided by 0\")"]}],"metadata":{"anaconda-cloud":{},"colab":{"provenance":[{"file_id":"1exgnaqzWKQfBSjodOeyZa0P6sxSZKb5P","timestamp":1751450169177}]},"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"}},"nbformat":4,"nbformat_minor":0}